/*
 * TaDaFinalAboutBox.java
 */

package tadagui;
import java.awt.BorderLayout;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

import org.jdesktop.application.Action;
import org.jdesktop.application.Application;


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
public class AnonymizationResultBox extends javax.swing.JDialog {

	
	private JLabel jLabel3;
	private JLabel jLabel2;
	private JLabel jLabel1;
	double total=0.0, anonymizationScore = 0.0,  timeTaken = 0.0, uniqueRecords = 0.0;
    public AnonymizationResultBox(java.awt.Frame parent, double totalRecords, double anonymizationScore, double timeTaken, double numberOfUniqueRecords,
    		double uniquenessScore) {
        super(parent);
        this.total = totalRecords;
        this.anonymizationScore = anonymizationScore;
        this.timeTaken = timeTaken;
        this.uniqueRecords = numberOfUniqueRecords;
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	JPanel mainPanel = new javax.swing.JPanel();
    	GroupLayout mainPanelLayout = new GroupLayout((JComponent)mainPanel);
    	mainPanel.setLayout(mainPanelLayout);
        javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel locLabel = new javax.swing.JLabel();
        javax.swing.JLabel percentLabel = new javax.swing.JLabel();
        
        BorderLayout layout = new BorderLayout();
        getContentPane().setLayout(layout);
        //BoxLayout layout = new BoxLayout((JComponent)getContentPane(), 2);
        //getContentPane().setLayout(layout);
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("coverageInfo"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(TaDaFinalApp.class).getContext().getActionMap(AnonymizationResultBox.class, this);

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        ; // NOI18N
        appTitleLabel.setName("appTitleLabel"); // NOI18N

        locLabel.setFont(locLabel.getFont().deriveFont(locLabel.getFont().getStyle() | java.awt.Font.BOLD));
        ; // NOI18N
        locLabel.setName("versionLabel"); // NOI18N
        locLabel.setText("Time Taken: " + timeTaken);

        {
        	closeButton = new javax.swing.JButton();
        	closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        	closeButton.setName("closeButton"); // NOI18N
        }
        {
        	jLabel1 = new JLabel();
        	jLabel1.setName("jLabel1");
        	jLabel1.setText("Anonymization Score: " + anonymizationScore);
        }
        {
        	jLabel2 = new JLabel();
        	jLabel2.setName("jLabel2");
        	jLabel2.setText("#Unique Records in Permuted Tables: " + uniqueRecords);
        }
        {
        	jLabel3 = new JLabel();
        	jLabel3.setName("jLabel3");
        	jLabel3.setText("Total Records In Permuted Tables: " + total);
        }
        	mainPanelLayout.setVerticalGroup(mainPanelLayout.createSequentialGroup()
        		.addContainerGap()
        		.addGroup(mainPanelLayout.createParallelGroup()
        		    .addComponent(locLabel, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
        		    .addGroup(GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
        		        .addGap(7)
        		        .addComponent(appTitleLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		        .addGap(7)))
        		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        		.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        		.addGroup(mainPanelLayout.createParallelGroup()
        		    .addComponent(jLabel2, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		    .addGroup(GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
        		        .addGap(7)
        		        .addComponent(percentLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		        .addGap(7)))
        		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        		.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addGap(27)
        		.addComponent(closeButton, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        		.addContainerGap(35, Short.MAX_VALUE));
        	mainPanelLayout.setHorizontalGroup(mainPanelLayout.createSequentialGroup()
        		.addContainerGap()
        		.addComponent(percentLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addGap(16)
        		.addComponent(appTitleLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        		.addGroup(mainPanelLayout.createParallelGroup()
        		    .addGroup(mainPanelLayout.createSequentialGroup()
        		        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
        		        .addGap(0, 0, Short.MAX_VALUE))
        		    .addGroup(GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
        		        .addComponent(locLabel, GroupLayout.PREFERRED_SIZE, 252, GroupLayout.PREFERRED_SIZE)
        		        .addGap(0, 16, Short.MAX_VALUE))
        		    .addGroup(mainPanelLayout.createSequentialGroup()
        		        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
        		        .addGap(0, 0, Short.MAX_VALUE))
        		    .addGroup(GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
        		        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
        		        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE))
        		    .addGroup(GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
        		        .addGap(79)
        		        .addComponent(closeButton, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
        		        .addGap(0, 77, Short.MAX_VALUE)))
        		.addContainerGap(34, 34));
        this.setContentPane(mainPanel);
        mainPanel.setPreferredSize(new java.awt.Dimension(436, 183));
        pack();
        this.setSize(342, 204);
        //this.setSize(280, 223);
        Application.getInstance().getContext().getResourceMap(getClass()).injectComponents(getContentPane());
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
    
}
