/*
 * TaDaFinalAboutBox.java
 */

package tadagui;
import java.awt.BorderLayout;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

import org.jdesktop.application.Action;
import org.jdesktop.application.Application;


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
public class ErrorBox extends javax.swing.JDialog {

	String message;
    public ErrorBox(java.awt.Frame parent, String message) {
        super(parent);
        this.message = message;
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	JPanel mainPanel = new javax.swing.JPanel();
    	GroupLayout mainPanelLayout = new GroupLayout((JComponent)mainPanel);
    	mainPanel.setLayout(mainPanelLayout);
        javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel locLabel = new javax.swing.JLabel();
        javax.swing.JLabel percentLabel = new javax.swing.JLabel();
        
        BorderLayout layout = new BorderLayout();
        getContentPane().setLayout(layout);
        //BoxLayout layout = new BoxLayout((JComponent)getContentPane(), 2);
        //getContentPane().setLayout(layout);
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(TaDaFinalApp.class).getContext().getResourceMap(ErrorBox.class);
        
        setModal(true);
        setName("coverageInfo"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(TaDaFinalApp.class).getContext().getActionMap(ErrorBox.class, this);

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        ; // NOI18N
        appTitleLabel.setName("appTitleLabel"); // NOI18N

        locLabel.setFont(locLabel.getFont().deriveFont(locLabel.getFont().getStyle() | java.awt.Font.BOLD));
        locLabel.setText("Error : " + message); // NOI18N
        locLabel.setName("versionLabel"); // NOI18N


        {
        	closeButton = new javax.swing.JButton();
        	closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        	closeButton.setName("closeButton"); // NOI18N
        }
        	mainPanelLayout.setVerticalGroup(mainPanelLayout.createSequentialGroup()
        		.addContainerGap(19, 19)
        		.addComponent(appTitleLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
        		.addComponent(locLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, 1, GroupLayout.PREFERRED_SIZE)
        		.addComponent(percentLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
        		.addComponent(closeButton, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		.addContainerGap());
        	mainPanelLayout.setHorizontalGroup(mainPanelLayout.createSequentialGroup()
        		.addContainerGap(28, 28)
        		.addGroup(mainPanelLayout.createParallelGroup()
        		    .addGroup(GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
        		        .addComponent(locLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		        .addGap(0, 22, Short.MAX_VALUE))
        		    .addGroup(mainPanelLayout.createSequentialGroup()
        		        .addComponent(percentLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		        .addGap(0, 0, Short.MAX_VALUE))
        		    .addGroup(GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
        		        .addGap(16)
        		        .addComponent(appTitleLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		        .addGap(24)
        		        .addComponent(closeButton, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        		        .addGap(0, 26, Short.MAX_VALUE)))
        		.addContainerGap(36, 36));
        this.setContentPane(mainPanel);
        pack();
        this.setSize(221, 142);
        //this.setSize(280, 223);
        Application.getInstance().getContext().getResourceMap(getClass()).injectComponents(getContentPane());
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables
    
}
